x-common-environment: &common-environment
  DB_HOST: postgres
  DB_NAME: item_data_db
  DB_USER: item_data_user
  DB_PASSWORD: secure_password_123

x-common-depends: &common-depends
  - postgres

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: item_data_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: item_data_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - item_data_network

  dash_app:
    build: ./dash_app
    ports:
      - "8050:8050"
    volumes:
      - ./dash_app:/dash_app
    depends_on: *common-depends
    environment: *common-environment
    restart: unless-stopped
    networks:
      - item_data_network

  data_collection_blood_runes:
    build: ./data_collector
    command: ["--item", "565"]
    depends_on: *common-depends
    environment: *common-environment
    restart: unless-stopped
    networks:
      - item_data_network

  data_collection_bird_nests:
    build: ./data_collector
    command: ["--item", "5075"]
    depends_on: *common-depends
    environment: *common-environment
    restart: unless-stopped
    networks:
      - item_data_network

  data_collection_oak_planks:
    build: ./data_collector
    command: ["--item", "8778"]
    depends_on: *common-depends
    environment: *common-environment
    restart: unless-stopped
    networks:
      - item_data_network

  data_collection_dragon_bones:
    build: ./data_collector
    command: ["--item", "536"]
    depends_on: *common-depends
    environment: *common-environment
    restart: unless-stopped
    networks:
      - item_data_network

networks:
  item_data_network:
    driver: bridge
